// PROBLEM 1

// If we list all the natural numbers below 10
//that are multiples of 3 or 5, we get 3, 5, 6 and 9.
//The sum of these multiples is 23. Find the sum of
//all the multiples of 3 or 5 below the
//provided parameter value number

function multiplesOf3and5(number) {
  var sum = 0;
  for (var i = 0; i < number; i++) {
    if (i%3 == 0 || i%5 == 0) {
      sum += i;
    }
  console.log(sum)
  }
}

// PROBLEM 2



//Each new term in the Fibonacci sequence is generated by
//adding the previous two terms. By starting with 1 and 2,
//the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence
//whose values do not exceed n, find the sum of the
//even-valued terms.



function fiboEvenSum(n) {
  var total = 0;
  var sum = 0;
  var fib1 = 1;
  var fib2 = 2;
  while (total < n) {
    total = fib1 + fib2;
    fib1 = fib2;
    fib2 = total;
    if(fib1 % 2 == 0) {
      sum += fib1;
    }
  }
  return sum;
}
